// app/layout.tsx
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* 暂时不用 next/font，避免构建时的字体依赖问题 */}
      <body className="font-sans">{children}</body>
    </html>
  );
}
